/** Короткі фрази для генерації семплів голосів (3-8 слів, рідною мовою) */
export const SAMPLE_TEXTS: Record<string, string> = {
  uk: 'Привіт! Ось так звучить мій голос.',
  en: 'Hi there! This is how I sound.',
  fr: 'Bonjour ! Voici le son de ma voix.',
  de: 'Hallo! So klingt meine Stimme.',
  es: '¡Hola! Así suena mi voz.',
  pt: 'Olá! É assim que soa a minha voz.',
  zh: '你好！这是我的声音。',
  ja: 'こんにちは！これが私の声です。',
  hi: 'नमस्ते! मेरी आवाज़ ऐसी है।',
  it: 'Ciao! Ecco come suona la mia voce.',
  ko: '안녕하세요! 제 목소리입니다.',
  nl: 'Hallo! Zo klinkt mijn stem.',
  pl: 'Cześć! Tak brzmi mój głos.',
  ru: 'Привет! Вот так звучит мой голос.',
  sv: 'Hej! Så här låter min röst.',
  tr: 'Merhaba! Sesim böyle geliyor.',
  tl: 'Kumusta! Ganito ang boses ko.',
  bg: 'Здравей! Така звучи гласът ми.',
  ro: 'Salut! Așa sună vocea mea.',
  ar: 'مرحباً! هذا هو صوتي.',
  cs: 'Ahoj! Takhle zní můj hlas.',
  el: 'Γεια σας! Έτσι ακούγεται η φωνή μου.',
  fi: 'Hei! Tältä ääneni kuulostaa.',
  hr: 'Bok! Ovako zvuči moj glas.',
  ms: 'Hai! Beginilah bunyi suara saya.',
  sk: 'Ahoj! Takto znie môj hlas.',
  da: 'Hej! Sådan lyder min stemme.',
  ta: 'வணக்கம்! இது என் குரல்.',
  hu: 'Szia! Így szól a hangom.',
  no: 'Hei! Slik høres stemmen min ut.',
  vi: 'Xin chào! Đây là giọng của tôi.',
  bn: 'হ্যালো! এটাই আমার কণ্ঠস্বর।',
  th: 'สวัสดี! นี่คือเสียงของฉัน',
  he: 'שלום! כך נשמע הקול שלי.',
  ka: 'გამარჯობა! ასე ჟღერს ჩემი ხმა.',
  id: 'Halo! Beginilah suara saya.',
  te: 'హలో! ఇది నా స్వరం.',
  gu: 'નમસ્તે! આ મારો અવાજ છે.',
  kn: 'ನಮಸ್ಕಾರ! ಇದು ನನ್ನ ಧ್ವನಿ.',
  ml: 'ഹലോ! ഇതാണ് എന്റെ ശബ്ദം.',
  mr: 'नमस्कार! हा माझा आवाज आहे.',
  pa: 'ਸਤ ਸ੍ਰੀ ਅਕਾਲ! ਇਹ ਮੇਰੀ ਆਵਾਜ਼ ਹੈ।'
}

export function sampleTextFor(language?: string): string {
  return SAMPLE_TEXTS[language ?? ''] ?? SAMPLE_TEXTS.en
}
