const t = await (await fetch('https://clerk.cartesia.ai/npm/@clerk/clerk-js@6/dist/clerk.browser.js')).text()
console.log('=== sK region (226050..228300) ===')
console.log(t.slice(226050, 228300).replace(/\n/g, ' '))
console.log('\n=== basePatch def ===')
const i = t.indexOf('_basePatch=')
console.log(t.slice(Math.max(0, i - 400), i + 500).replace(/\n/g, ' '))
console.log('\n=== bootstrap.js (first 3000) ===')
const b = await (await fetch('https://cdn.protect.clerk.com/ins_2dkzDoDZRl1ShmWomHR110Rr5EY/c/1-m4uicibgm6t3qkxkguyhtgbryy-mxu7qsqn4wgirnhbewjqqq7ixq/bootstrap.js?v=6.30.1', { headers: { 'User-Agent': 'Mozilla/5.0' } })).text()
console.log(b.slice(0, 3000))
console.log('... len=' + b.length)
